<?php
require_once __DIR__ . '/../config/config.php';
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../includes/auth.php';

$user = current_user();
if (($user['role'] ?? '') !== 'admin') {
    flash_set('error', 'Only administrators can run backups.');
    redirect('index.php');
}

if (isset($_GET['download']) && db_ok()) {
    // Stream a SQL dump of every table
    while (ob_get_level() > 0) ob_end_clean();
    audit_log('export', 'database', null, 'Full SQL backup');

    $filename = 'backup-' . DB_NAME . '-' . date('Ymd-His') . '.sql';
    header('Content-Type: application/sql; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Cache-Control: no-store');

    echo "-- " . DB_NAME . " backup · " . date('c') . "\n";
    echo "-- Generated by " . APP_NAME . "\n\n";
    echo "SET FOREIGN_KEY_CHECKS=0;\n";
    echo "SET NAMES utf8mb4;\n\n";

    $tables = db()->query("SHOW TABLES")->fetchAll(PDO::FETCH_COLUMN);
    foreach ($tables as $t) {
        // Schema
        echo "-- ----- $t -----\n";
        echo "DROP TABLE IF EXISTS `$t`;\n";
        $row = db()->query("SHOW CREATE TABLE `$t`")->fetch(PDO::FETCH_NUM);
        echo $row[1] . ";\n\n";

        // Data
        $rows = db()->query("SELECT * FROM `$t`")->fetchAll(PDO::FETCH_ASSOC);
        if (!$rows) continue;
        $cols = '`' . implode('`,`', array_keys($rows[0])) . '`';
        foreach (array_chunk($rows, 100) as $batch) {
            $values = [];
            foreach ($batch as $r) {
                $vs = [];
                foreach ($r as $v) {
                    if ($v === null)            $vs[] = 'NULL';
                    elseif (is_numeric($v))     $vs[] = $v;
                    else                        $vs[] = db()->quote((string)$v);
                }
                $values[] = '(' . implode(',', $vs) . ')';
            }
            echo "INSERT INTO `$t` ($cols) VALUES\n  " . implode(",\n  ", $values) . ";\n";
        }
        echo "\n";
    }
    echo "SET FOREIGN_KEY_CHECKS=1;\n";
    exit;
}

$pageTitle = 'Database Backup';
require_once __DIR__ . '/../includes/header.php';

$tables = $sizes = [];
if (db_ok()) {
    $tables = db()->query("SHOW TABLES")->fetchAll(PDO::FETCH_COLUMN);
    $stmt = db()->query("
        SELECT table_name AS t, table_rows AS rows, ROUND(data_length/1024,1) AS kb
        FROM information_schema.tables
        WHERE table_schema = '" . DB_NAME . "'
    ");
    foreach ($stmt->fetchAll() as $r) $sizes[strtolower($r['t'])] = $r;
}
?>

<div class="page-head">
    <div>
        <h1>Database Backup</h1>
        <div class="crumbs"><a href="index.php">Home</a> / Backup</div>
    </div>
</div>

<?= db_banner_if_offline() ?>
<?= render_flash() ?>

<div class="card" style="max-width:780px;">
    <div class="card-h"><h3><i class="bi bi-download"></i> Download Full SQL Backup</h3></div>

    <div style="background:rgba(var(--accent-rgb),.08);border:1px solid rgba(var(--accent-rgb),.3);border-radius:10px;padding:14px 18px;font-size:13px;color:var(--accent-dark);margin-bottom:18px;">
        <i class="bi bi-shield-check"></i>
        Generates a full <code>.sql</code> dump of every table (schema + data) and forces a download. Run this regularly — recommended weekly. The download is audit-logged with your user, IP, and timestamp.
    </div>

    <a href="backup.php?download=1" class="btn btn-primary" style="font-size:15px;padding:12px 22px;">
        <i class="bi bi-cloud-download-fill"></i> Download <?= e(DB_NAME) ?>.sql
    </a>

    <div style="margin-top:24px;">
        <h4 style="font-size:14px;color:var(--primary);margin-bottom:10px;"><i class="bi bi-table"></i> Tables in this database</h4>
        <table class="tbl">
            <thead><tr><th>#</th><th>Table</th><th>Rows</th><th>Data size</th></tr></thead>
            <tbody>
            <?php foreach ($tables as $i => $t):
                $info = $sizes[strtolower($t)] ?? null;
            ?>
                <tr>
                    <td><?= $i+1 ?></td>
                    <td><code><?= e($t) ?></code></td>
                    <td><?= $info ? number_format((int)$info['rows']) : '—' ?></td>
                    <td><?= $info ? number_format((float)$info['kb'], 1) . ' KB' : '—' ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<div class="card" style="margin-top:18px;max-width:780px;background:rgba(var(--primary-rgb),.04);">
    <h4 style="font-size:14px;color:var(--primary);margin-bottom:10px;"><i class="bi bi-info-circle"></i> Restore</h4>
    <p style="font-size:13px;color:var(--muted);margin:0;">
        To restore: drop your current database, create an empty one, then run<br>
        <code style="background:#fff;padding:3px 8px;border-radius:5px;">mysql -u root -p <?= e(DB_NAME) ?> &lt; backup-file.sql</code><br>
        or import via phpMyAdmin → Import.
    </p>
</div>

<?php require_once __DIR__ . '/../includes/footer.php'; ?>
